# Generated by Django 4.1.3 on 2022-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_order_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_tb',
        ),
        migrations.AddField(
            model_name='register_tb',
            name='hashpass',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
